# Data Preprocessing Tools

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
# from google.colab import drive
# drive.mount('/My Drive/MyWorkshop')
print ("Nothing")

Nothing


In [ ]:

path = "D:/MyGithubSource/Machine Learning A-Z/Part 1 - Data Preprocessing/Section-2-Part-1-Data Preprocessing/Python/"
dataset = pd.read_csv(path + 'Data.csv')


In [7]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

Independent Variables: These are the features or input variables that are used to make a prediction. In this case, the model will use the country, age, and salary of a customer to try and predict their purchase behavior.

Dependent Variable: This is the target or output variable that the model is trying to predict. It is called "dependent" because its value is expected to depend on the independent variables. In this dataset, 'Purchased' is the dependent variable, which likely has a binary outcome (e.g., Yes/No)

here in this example..

Country, age and salary are independent variables 
purchased is a dependent variable 

In [ ]:
# Selects the the first three columns (except the last one) / features - country, age, salary
X = dataset.iloc[:, :-1].values

# select the last column 
y = dataset.iloc[:, -1].values
print(X)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# typically you use this method to select and apply this to all the numerical columns
# fit method will look at the missing valkues of the salary column and will calculate the average salary 
imputer.fit(X[:, 1:3])

# transform method will apply the changes to those rows
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [11]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In this example we have three distinct 

### Encoding the Independent Variable

In [14]:
print (X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# What happens below in the ColumnTransformer
# kind of transformation = encoding, what kind of encoding = one hot encoding
# third is the index of the column we want to encode [0] i.e. the country column
# remainder = 'passthrough' (leaves the other columns out of encoding)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# we need the output to be a numpy array as the train function further down the line will expect that
X = np.array(ct.fit_transform(X))

In [16]:
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable (Y-variable)

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [18]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

Here we split the dataset into two - training set and the test set 

What the split 
the training set is used to train the machine learning model  
the test set is used to evaluate the performance of the model based on these new observations

Then apply the feature scaling 
Why ? Becasue applying the scaling to the entire data set will consider the means / averages of the entire population this will skew the test set values i.e. it will induce information leakage

So ..to avoid this .. split the dataset first and then apply the feature scaling 

What should the split ratio be?
Recommended 80:20 



In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [23]:
print(X_train)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [24]:
print(X_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [25]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [26]:
print(y_test)

[0 1]


## Feature Scaling

Why feature scaling ?
To avoid some features from dominating the narrative the results.

Ex. 

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [28]:
print(X_train)

[[ 0.77459667 -0.77459667 -0.57735027  1.29099445 -0.19159184 -1.07812594]
 [ 0.77459667 -0.77459667  1.73205081 -0.77459667 -0.01411729 -0.07013168]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667  0.56670851  0.63356243]
 [ 0.77459667 -0.77459667 -0.57735027  1.29099445 -0.30453019 -0.30786617]
 [ 0.77459667 -0.77459667 -0.57735027  1.29099445 -1.90180114 -1.42046362]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667  1.14753431  1.23265336]
 [ 0.77459667 -0.77459667  1.73205081 -0.77459667  1.43794721  1.57499104]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667 -0.74014954 -0.56461943]]


In [29]:
print(X_test)

[[ 0.77459667 -0.77459667  1.73205081 -0.77459667 -1.46618179 -0.9069571 ]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667 -0.44973664  0.20564034]]
